/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 *  led_button
 *
 *
 *      Author: Yin
 */

#include <stdint.h>
#include "stm32f407xx.h"
#include "stm32f407xx_gpio_driver.h"

#define HIGH        1
#define BTN_PRESSED HIGH

void delay(void);

// toggle_LED
int main(void){

	GPIO_Handle_t GPIOLed, GPIOBtn;

	//push-pull
	GPIOLed.pGPIOx = GPIOD;
	GPIOLed.GPIO_PinConfig.GPIO_PinNumber      = GPIO_PIN_NO_12;
	GPIOLed.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
	GPIOLed.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_SPD_VHIGH;
	GPIOLed.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OP_TYPE_PP;
	GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIOLed.GPIO_PinConfig.GPIO_PinAltFunMode  = 0;

	//open-drain (若使用內部上拉電阻=>電阻太大，會使LED無法閃爍，因此需要外接一個外部電阻)
//	GPIOLed.pGPIOx = GPIOD;
//	GPIOLed.GPIO_PinConfig.GPIO_PinNumber      = GPIO_PIN_NO_12;
//	GPIOLed.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_OUT;
//	GPIOLed.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_SPD_VHIGH;
//	GPIOLed.GPIO_PinConfig.GPIO_PinOPType      = GPIO_OP_TYPE_OD;
//	GPIOLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PU;
//	GPIOLed.GPIO_PinConfig.GPIO_PinAltFunMode  = 0;

	GPIO_PeriClockControl(GPIOD, ENABLE);

	GPIO_Init(&GPIOLed);

	GPIOBtn.pGPIOx = GPIOA;
	GPIOBtn.GPIO_PinConfig.GPIO_PinNumber      = GPIO_PIN_NO_0;
	GPIOBtn.GPIO_PinConfig.GPIO_PinMode        = GPIO_MODE_IN;
	GPIOBtn.GPIO_PinConfig.GPIO_PinSpeed       = GPIO_SPD_VHIGH;
	GPIOBtn.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GPIOBtn.GPIO_PinConfig.GPIO_PinAltFunMode  = 0;


	GPIO_PeriClockControl(GPIOA, ENABLE);

	GPIO_Init(&GPIOBtn);

	while (1){
		if (GPIO_ReadFromInputPin(GPIOA, GPIO_PIN_NO_0) == BTN_PRESSED){
			delay();
			GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		}

	}

	return 0;
}


void delay(void){
	for (uint32_t i = 0; i < 250000; i++);
}
